import type { Metadata } from 'next';
import '../styles/globals.scss';
import StateContextProvider from '@/context/StateCtx';
import { nunito, workSans, poppins } from '@/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateContextProvider>
        <body
          className={`${nunito.className} ${workSans.variable} ${poppins.variable}`}
        >
          {children}
        </body>
      </StateContextProvider>
    </html>
  );
}
